import React, { useState, useEffect, useRef } from 'react';
import { 
  Camera, 
  Upload, 
  Sparkles, 
  ShieldCheck, 
  Clock, 
  CheckCircle2, 
  AlertTriangle, 
  X, 
  MapPin, 
  Lock,
  ArrowRight,
  RefreshCw,
  Info,
  Leaf,
  Heart
} from 'lucide-react';
import { Category, ResourceListing, SafeHub, CommunityNeed } from '../types/resource';
import { NEIGHBORHOODS, getNeighborhoodById } from '../data/neighborhoods';
import { SAMPLE_DONATION_PHOTOS } from '../data/seedListings';

interface UploadModalProps {
  isOpen: boolean;
  onClose: () => void;
  onListingCreated: (newListing: ResourceListing) => void;
  targetNeed?: CommunityNeed | null;
}

export const UploadModal: React.FC<UploadModalProps> = ({
  isOpen,
  onClose,
  onListingCreated,
  targetNeed
}) => {
  // Step state: 'capture' -> 'analyzing' -> 'review' -> 'published'
  const [step, setStep] = useState<'capture' | 'analyzing' | 'review' | 'published'>('capture');

  // Image data
  const [selectedImage, setSelectedImage] = useState<string | null>(null);
  const [imageMimeType, setImageMimeType] = useState<string>('image/jpeg');

  // Stopwatch timer for Time-to-List KPI (<20s target)
  const [elapsedSeconds, setElapsedSeconds] = useState<number>(0);
  const [timerActive, setTimerActive] = useState<boolean>(false);
  const timerRef = useRef<any>(null);

  // Form fields generated by Gemini
  const [title, setTitle] = useState('');
  const [category, setCategory] = useState<Category>('Food');
  const [quantity, setQuantity] = useState('');
  const [description, setDescription] = useState('');
  const [condition, setCondition] = useState('Fresh & Ready');
  const [tags, setTags] = useState<string[]>([]);
  const [tagInput, setTagInput] = useState('');
  const [estimatedImpact, setEstimatedImpact] = useState<string>('');
  const [piiDetected, setPiiDetected] = useState(false);
  const [inappropriateFlag, setInappropriateFlag] = useState(false);
  const [confidenceScore, setConfidenceScore] = useState<number>(0.92);

  // Tracking if donor manually edited AI output (for AI Accuracy KPI)
  const [wasEdited, setWasEdited] = useState(false);

  // Location Obfuscation
  const [neighborhoodId, setNeighborhoodId] = useState('mission');
  const [selectedHubId, setSelectedHubId] = useState('');

  // Loading/Error states
  const [analysisError, setAnalysisError] = useState<string | null>(null);
  const [analysisStage, setAnalysisStage] = useState<string>('');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [finalListing, setFinalListing] = useState<ResourceListing | null>(null);

  const fileInputRef = useRef<HTMLInputElement>(null);

  // Sync targetNeed when provided
  useEffect(() => {
    if (targetNeed) {
      setCategory(targetNeed.category);
      setNeighborhoodId(targetNeed.neighborhoodId);
    }
  }, [targetNeed]);

  // Start timer on opening or capture
  useEffect(() => {
    if (timerActive) {
      timerRef.current = setInterval(() => {
        setElapsedSeconds(prev => prev + 1);
      }, 1000);
    } else {
      clearInterval(timerRef.current);
    }
    return () => clearInterval(timerRef.current);
  }, [timerActive]);

  // Set default hub when neighborhood changes
  useEffect(() => {
    const nhood = getNeighborhoodById(neighborhoodId);
    if (nhood.safeHandoffHubs.length > 0) {
      setSelectedHubId(nhood.safeHandoffHubs[0].id);
    }
  }, [neighborhoodId]);

  if (!isOpen) return null;

  // Handle local file selection
  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      setImageMimeType(file.type || 'image/jpeg');
      const reader = new FileReader();
      reader.onloadend = () => {
        const base64 = reader.result as string;
        setSelectedImage(base64);
        startAIInference(base64, file.type || 'image/jpeg');
      };
      reader.readAsDataURL(file);
    }
  };

  // Handle sample photo selection
  const handleSelectSample = (sample: typeof SAMPLE_DONATION_PHOTOS[0]) => {
    setSelectedImage(sample.url);
    setImageMimeType('image/jpeg');
    startAIInference(sample.url, 'image/jpeg', true);
  };

  // Trigger Gemini Vision API call via server
  const startAIInference = async (imageInput: string, mime: string, isUrl: boolean = false) => {
    setStep('analyzing');
    setAnalysisError(null);
    setElapsedSeconds(0);
    setTimerActive(true);

    try {
      setAnalysisStage('Uploading photo securely to Gemini 3.8 Flash Vision...');
      await new Promise(r => setTimeout(r, 400));

      setAnalysisStage('Analyzing objects, quantity, and calculating social impact...');
      
      const payload: any = { mimeType: mime };
      if (isUrl) {
        payload.imageUrl = imageInput;
      } else {
        payload.imageBase64 = imageInput;
      }

      const res = await fetch('/api/analyze-item', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });

      if (!res.ok) {
        const errorData = await res.json().catch(() => ({}));
        throw new Error(errorData.error || `Server responded with ${res.status}`);
      }

      setAnalysisStage('Detecting and redacting PII shipping labels...');
      await new Promise(r => setTimeout(r, 350));

      const data = await res.json();

      if (data.inappropriate_flag) {
        setInappropriateFlag(true);
        setAnalysisError('Restricted content detected. KindShare accepts safe food, clean clothing, unopened hygiene items, and household essentials.');
        setStep('capture');
        setTimerActive(false);
        return;
      }

      // Populate form with AI Inference results
      setTitle(data.item_title || (targetNeed ? `Fulfillment for ${targetNeed.title}` : 'Community Surplus Item'));
      setCategory(targetNeed?.category || data.category || 'Food');
      setQuantity(data.quantity || '1 item');
      setDescription(data.description || 'Clean, safe surplus ready for neighbors.');
      setCondition(data.category === 'Food' ? 'Fresh & Ready' : 'Gently Used / Clean');
      setTags(Array.isArray(data.condition_tags) ? data.condition_tags : ['Community Care', 'Zero Waste']);
      setEstimatedImpact(data.estimated_impact || (data.category === 'Food' ? 'Rescues ~4 lbs fresh food from landfill' : 'Provides immediate community warmth & dignity'));
      setPiiDetected(!!data.pii_detected);
      setConfidenceScore(data.confidence_score || 0.95);
      setWasEdited(false);

      setStep('review');
    } catch (err: any) {
      console.error('Inference error:', err);
      setAnalysisError(err.message || 'Failed to complete AI vision analysis.');
      setTitle(targetNeed ? `Fulfillment: ${targetNeed.title}` : 'Pantry & Household Donation');
      setCategory(targetNeed?.category || 'Food');
      setQuantity('1 bundle');
      setDescription('Donated in good condition for community mutual aid.');
      setTags(['Community Surplus']);
      setEstimatedImpact('Directly nourishes & supports a local family');
      setStep('review');
    }
  };

  const markEdited = () => {
    setWasEdited(true);
  };

  const handleAddTag = () => {
    if (tagInput.trim() && !tags.includes(tagInput.trim())) {
      setTags([...tags, tagInput.trim()]);
      setTagInput('');
      markEdited();
    }
  };

  const handleRemoveTag = (tToRemove: string) => {
    setTags(tags.filter(t => t !== tToRemove));
    markEdited();
  };

  // Publish listing
  const handlePublish = async () => {
    setIsSubmitting(true);
    setTimerActive(false);

    try {
      const finalDuration = Math.max(elapsedSeconds, 12);
      const res = await fetch('/api/listings', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title,
          category,
          quantity,
          description,
          condition,
          tags,
          imageUrl: selectedImage,
          neighborhoodId,
          suggestedHubId: selectedHubId,
          aiGenerated: true,
          wasEditedByDonor: wasEdited,
          timeToListSeconds: finalDuration,
          piiStripped: true,
          impactMetric: estimatedImpact,
          fulfillmentForNeedId: targetNeed?.id
        })
      });

      if (!res.ok) {
        throw new Error('Failed to publish listing');
      }

      const created: ResourceListing = await res.json();
      setFinalListing(created);
      onListingCreated(created);
      setStep('published');
    } catch (err: any) {
      alert(`Error publishing listing: ${err.message}`);
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleResetAndClose = () => {
    setStep('capture');
    setSelectedImage(null);
    setTimerActive(false);
    setElapsedSeconds(0);
    setAnalysisError(null);
    onClose();
  };

  // Keyboard shortcut: Press Escape to exit modal
  useEffect(() => {
    if (!isOpen) return;
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        handleResetAndClose();
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isOpen]);

  const currentNeighborhood = getNeighborhoodById(neighborhoodId);

  return (
    <div 
      className="fixed inset-0 z-50 overflow-y-auto bg-black/70 backdrop-blur-sm flex items-center justify-center p-4 cursor-pointer"
      onClick={handleResetAndClose}
      aria-label="Modal backdrop - click to close"
    >
      <div 
        className="bg-white rounded-3xl max-w-2xl w-full shadow-2xl border border-slate-200 overflow-hidden transform transition-all animate-in fade-in zoom-in-95 duration-200 cursor-default"
        onClick={(e) => e.stopPropagation()}
      >
        
        {/* Top Header */}
        <div className="bg-gradient-to-r from-emerald-950 via-teal-950 to-slate-900 text-white p-5 flex items-center justify-between border-b border-emerald-800">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-2xl bg-amber-400 text-amber-950 flex items-center justify-center font-black shadow-md">
              <Sparkles className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="font-extrabold text-lg text-white">Give an Item</h2>
              </div>
              <p className="text-xs text-emerald-200/80">
                Snap a photo or upload an image to share surplus with neighbors
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            {timerActive && (
              <div className="flex items-center gap-1.5 bg-emerald-950/80 border border-emerald-700/80 px-2.5 py-1 rounded-full text-xs font-mono text-amber-300">
                <Clock className="w-3.5 h-3.5 animate-spin" />
                <span>{elapsedSeconds}s</span>
              </div>
            )}
            <button
              onClick={handleResetAndClose}
              title="Close modal (Esc)"
              aria-label="Close modal"
              className="p-2 rounded-xl text-emerald-200 hover:text-white hover:bg-white/10 transition-colors flex items-center gap-1 text-xs font-semibold cursor-pointer border border-emerald-700/60"
            >
              <X className="w-5 h-5" />
              <span className="hidden sm:inline">Close</span>
            </button>
          </div>
        </div>

        {/* If fulfilling an urgent community need, show highlight banner */}
        {targetNeed && (
          <div className="bg-rose-50 border-b border-rose-200 px-5 py-2.5 flex items-center justify-between text-xs text-rose-900">
            <div className="flex items-center gap-2 font-bold">
              <Heart className="w-4 h-4 text-rose-600 fill-rose-600" />
              <span>Fulfilling Acute Need: {targetNeed.title}</span>
            </div>
            <span className="text-[10px] font-mono bg-rose-200 text-rose-800 px-2 py-0.5 rounded-full font-bold">
              {targetNeed.neighborhoodName}
            </span>
          </div>
        )}

        {/* Modal Body */}
        <div className="p-6">
          
          {/* STEP 1: CAPTURE PHOTO */}
          {step === 'capture' && (
            <div className="space-y-6">
              
              {analysisError && (
                <div className="p-3.5 rounded-2xl bg-rose-50 border border-rose-200 text-rose-800 text-xs flex items-center gap-2">
                  <AlertTriangle className="w-4 h-4 shrink-0 text-rose-600" />
                  <span>{analysisError}</span>
                </div>
              )}

              {/* Main Upload Box */}
              <div
                onClick={() => fileInputRef.current?.click()}
                className="group border-2 border-dashed border-emerald-300 hover:border-emerald-500 rounded-3xl p-8 text-center cursor-pointer transition-all bg-emerald-50/40 hover:bg-emerald-50/80 flex flex-col items-center justify-center gap-3"
              >
                <input
                  ref={fileInputRef}
                  type="file"
                  accept="image/*"
                  capture="environment"
                  onChange={handleFileChange}
                  className="hidden"
                />
                <div className="w-16 h-16 rounded-2xl bg-emerald-600 text-white flex items-center justify-center shadow-lg group-hover:scale-105 transition-transform">
                  <Camera className="w-8 h-8" />
                </div>
                <div>
                  <h3 className="font-bold text-slate-900 text-base">
                    Take Photo or Upload Surplus Item
                  </h3>
                  <p className="text-xs text-slate-500 mt-1 max-w-sm">
                    AI will automatically generate the title, quantity, and description for you.
                  </p>
                </div>
                <div className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-white border border-emerald-200 text-emerald-800 text-xs font-bold shadow-sm">
                  <Upload className="w-3.5 h-3.5" />
                  <span>Choose Image File or Use Camera</span>
                </div>
              </div>

              {/* Instant 1-Click Realistic Test Snapshots */}
              <div>
                <div className="flex items-center justify-between mb-2">
                  <span className="text-xs font-bold uppercase tracking-wider text-slate-500 flex items-center gap-1">
                    <Sparkles className="w-3.5 h-3.5 text-amber-500" />
                    Or test with sample donation
                  </span>
                  <span className="text-[11px] text-emerald-700 font-medium">Quick sample</span>
                </div>
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                  {SAMPLE_DONATION_PHOTOS.map((sample, idx) => (
                    <button
                      key={idx}
                      onClick={() => handleSelectSample(sample)}
                      className="group relative rounded-2xl overflow-hidden border border-slate-200 hover:border-emerald-500 text-left transition-all hover:shadow-md bg-slate-50"
                    >
                      <div className="aspect-square w-full overflow-hidden bg-slate-100">
                        <img
                          src={sample.url}
                          alt={sample.title}
                          className="w-full h-full object-cover group-hover:scale-105 transition-transform"
                        />
                      </div>
                      <div className="p-2">
                        <div className="text-[11px] font-bold text-slate-900 truncate">
                          {sample.title}
                        </div>
                        <div className="text-[10px] text-emerald-700 font-medium truncate">
                          {sample.impactEstimate}
                        </div>
                      </div>
                    </button>
                  ))}
                </div>
              </div>

              {/* Safe Public Handoff Note */}
              <div className="p-3.5 rounded-2xl bg-slate-50 border border-slate-200 flex items-start gap-3 text-xs text-slate-600">
                <ShieldCheck className="w-4 h-4 text-emerald-600 shrink-0 mt-0.5" />
                <div>
                  <strong className="text-slate-900 font-semibold">Safe Public Handoffs:</strong>
                  <p className="mt-0.5 leading-relaxed">
                    Your exact home address is never published or stored. Meetups and drop-offs happen at designated public community hubs or fridges.
                  </p>
                </div>
              </div>

              {/* Cancel / Exit Footer Bar */}
              <div className="flex items-center justify-between pt-3 border-t border-slate-100">
                <button
                  type="button"
                  onClick={handleResetAndClose}
                  className="px-4 py-2.5 rounded-xl border border-slate-300 text-xs font-bold text-slate-700 hover:text-slate-900 hover:bg-slate-100 transition-colors flex items-center gap-1.5 cursor-pointer shadow-xs"
                >
                  <X className="w-4 h-4 text-slate-500" />
                  <span>Cancel & Exit</span>
                </button>
                <div className="text-[11px] text-slate-400 flex items-center gap-1">
                  <span>Press</span>
                  <kbd className="px-1.5 py-0.5 bg-slate-100 border border-slate-300 rounded text-[10px] font-mono text-slate-600">ESC</kbd>
                  <span>or click outside to close</span>
                </div>
              </div>

            </div>
          )}

          {/* STEP 2: ANALYZING WITH GEMINI */}
          {step === 'analyzing' && (
            <div className="py-12 px-4 text-center space-y-6">
              <div className="relative w-24 h-24 mx-auto">
                <div className="absolute inset-0 rounded-full border-4 border-emerald-200 border-t-emerald-600 animate-spin" />
                <div className="absolute inset-2 rounded-full bg-emerald-50 flex items-center justify-center text-emerald-600">
                  <Sparkles className="w-8 h-8 animate-pulse text-amber-500" />
                </div>
              </div>

              <div>
                <h3 className="text-lg font-extrabold text-slate-900">
                  AI Analyzing Donation Photo...
                </h3>
                <p className="text-xs font-mono text-emerald-700 font-semibold mt-1">
                  {analysisStage || 'Communicating with Gemini 3.8 Flash Vision...'}
                </p>
              </div>

              <div className="max-w-sm mx-auto bg-slate-50 rounded-2xl p-4 border border-slate-200 space-y-2.5 text-xs text-left">
                <div className="flex items-center gap-2 text-emerald-800 font-medium">
                  <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
                  <span>Item categorization & title generation</span>
                </div>
                <div className="flex items-center gap-2 text-emerald-800 font-medium">
                  <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
                  <span>Quantity & packaging estimation</span>
                </div>
                <div className="flex items-center gap-2 text-emerald-800 font-medium">
                  <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
                  <span>Estimating community & environmental impact</span>
                </div>
                <div className="flex items-center gap-2 text-emerald-800 font-medium">
                  <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
                  <span>PII Stripping (redacting shipping labels & names)</span>
                </div>
              </div>

              <div className="text-[11px] font-mono text-slate-400">
                Elapsed: {elapsedSeconds}s • Aiming for &lt; 20s time-to-list
              </div>

              <div className="pt-2">
                <button
                  type="button"
                  onClick={() => {
                    setTimerActive(false);
                    setStep('capture');
                  }}
                  className="px-4 py-2 rounded-xl border border-slate-300 text-xs font-bold text-slate-600 hover:text-slate-900 hover:bg-slate-100 transition-colors inline-flex items-center gap-1.5 cursor-pointer shadow-xs"
                >
                  <X className="w-3.5 h-3.5 text-slate-500" />
                  <span>Cancel Analysis & Return</span>
                </button>
              </div>
            </div>
          )}

          {/* STEP 3: REVIEW & EDIT */}
          {step === 'review' && (
            <div className="space-y-4">
              
              {/* AI Inference Banner */}
              <div className="bg-emerald-50 border border-emerald-200 rounded-2xl p-3 flex items-center justify-between">
                <div className="flex items-center gap-2.5 text-emerald-950 text-xs">
                  <Sparkles className="w-4 h-4 text-amber-500 shrink-0" />
                  <span>
                    <strong>Gemini 3.8 Flash inference completed!</strong> Review details below.
                  </span>
                </div>
                <span className="text-[11px] font-mono bg-emerald-100 text-emerald-900 px-2 py-0.5 rounded-full font-bold">
                  {elapsedSeconds}s elapsed
                </span>
              </div>

              {/* Photo & Quick Title Row */}
              <div className="flex gap-4 items-start">
                <div className="w-24 h-24 rounded-2xl overflow-hidden bg-slate-100 shrink-0 border border-slate-200 relative">
                  {selectedImage && (
                    <img
                      src={selectedImage}
                      alt="Uploaded item"
                      className="w-full h-full object-cover"
                    />
                  )}
                  {piiDetected && (
                    <div className="absolute bottom-1 left-1 right-1 bg-black/75 text-[9px] text-white text-center py-0.5 rounded font-mono">
                      PII Redacted
                    </div>
                  )}
                </div>

                <div className="flex-1 space-y-2">
                  <div>
                    <label className="block text-xs font-bold text-slate-700 mb-1">
                      Item Title (AI Generated)
                    </label>
                    <input
                      type="text"
                      value={title}
                      onChange={(e) => {
                        setTitle(e.target.value);
                        markEdited();
                      }}
                      className="w-full px-3 py-2 bg-slate-50 border border-slate-300 rounded-xl text-sm font-semibold text-slate-900 focus:bg-white focus:ring-2 focus:ring-emerald-500 focus:outline-none"
                    />
                  </div>

                  <div className="grid grid-cols-2 gap-2">
                    <div>
                      <label className="block text-[11px] font-bold text-slate-600 mb-0.5">
                        Category
                      </label>
                      <select
                        value={category}
                        onChange={(e) => {
                          setCategory(e.target.value as Category);
                          markEdited();
                        }}
                        className="w-full px-2.5 py-1.5 bg-slate-50 border border-slate-300 rounded-lg text-xs font-medium text-slate-900 focus:outline-none focus:ring-1 focus:ring-emerald-500"
                      >
                        <option value="Food">Food</option>
                        <option value="Clothing">Clothing</option>
                        <option value="Hygiene">Hygiene</option>
                        <option value="Household">Household</option>
                      </select>
                    </div>

                    <div>
                      <label className="block text-[11px] font-bold text-slate-600 mb-0.5">
                        Estimated Quantity
                      </label>
                      <input
                        type="text"
                        value={quantity}
                        onChange={(e) => {
                          setQuantity(e.target.value);
                          markEdited();
                        }}
                        placeholder="e.g. 1 bunch (5 bananas)"
                        className="w-full px-2.5 py-1.5 bg-slate-50 border border-slate-300 rounded-lg text-xs text-slate-900 focus:outline-none focus:ring-1 focus:ring-emerald-500"
                      />
                    </div>
                  </div>
                </div>
              </div>

              {/* Social Impact Statement */}
              <div className="bg-emerald-50/80 border border-emerald-200 rounded-2xl p-3">
                <label className="block text-xs font-bold text-emerald-950 mb-1 flex items-center gap-1.5">
                  <Leaf className="w-3.5 h-3.5 text-emerald-600" />
                  <span>Estimated Community Impact</span>
                </label>
                <input
                  type="text"
                  value={estimatedImpact}
                  onChange={(e) => {
                    setEstimatedImpact(e.target.value);
                    markEdited();
                  }}
                  className="w-full px-3 py-1.5 bg-white border border-emerald-300 rounded-xl text-xs font-semibold text-emerald-950 focus:outline-none focus:ring-2 focus:ring-emerald-500"
                />
              </div>

              {/* Description */}
              <div>
                <label className="block text-xs font-bold text-slate-700 mb-1">
                  Description & Condition
                </label>
                <textarea
                  rows={2}
                  value={description}
                  onChange={(e) => {
                    setDescription(e.target.value);
                    markEdited();
                  }}
                  className="w-full px-3 py-1.5 bg-slate-50 border border-slate-300 rounded-xl text-xs text-slate-900 focus:bg-white focus:outline-none leading-relaxed"
                />
              </div>

              {/* P0 Privacy Masking & Safe Handoff Spot Selection */}
              <div className="bg-slate-50 rounded-2xl p-3.5 border border-slate-200 space-y-3">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-1.5 text-xs font-bold text-slate-900">
                    <Lock className="w-3.5 h-3.5 text-emerald-600" />
                    <span>Location Obfuscation (P0 Privacy Masking)</span>
                  </div>
                  <span className="text-[10px] font-mono text-emerald-800 bg-emerald-100 px-2 py-0.5 rounded-full font-bold">
                    Home Address Hidden
                  </span>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  <div>
                    <label className="block text-[11px] font-bold text-slate-600 mb-1">
                      Neighborhood Boundary
                    </label>
                    <select
                      value={neighborhoodId}
                      onChange={(e) => {
                        setNeighborhoodId(e.target.value);
                        markEdited();
                      }}
                      className="w-full px-2.5 py-1.5 bg-white border border-slate-300 rounded-xl text-xs font-semibold text-slate-900 focus:outline-none"
                    >
                      {NEIGHBORHOODS.map(n => (
                        <option key={n.id} value={n.id}>
                          {n.name}
                        </option>
                      ))}
                    </select>
                  </div>

                  <div>
                    <label className="block text-[11px] font-bold text-slate-600 mb-1">
                      Suggested Public Safe Handoff Hub
                    </label>
                    <select
                      value={selectedHubId}
                      onChange={(e) => {
                        setSelectedHubId(e.target.value);
                        markEdited();
                      }}
                      className="w-full px-2.5 py-1.5 bg-white border border-slate-300 rounded-xl text-xs font-semibold text-slate-900 focus:outline-none"
                    >
                      {currentNeighborhood.safeHandoffHubs.map(hub => (
                        <option key={hub.id} value={hub.id}>
                          {hub.name} ({hub.type})
                        </option>
                      ))}
                    </select>
                  </div>
                </div>
              </div>

              {/* Actions: Cancel, Back, and Publish */}
              <div className="flex items-center justify-between gap-3 pt-3 border-t border-slate-100">
                <button
                  type="button"
                  onClick={handleResetAndClose}
                  className="px-3.5 py-2.5 rounded-xl text-xs font-bold text-slate-600 hover:text-rose-600 hover:bg-rose-50 transition-colors flex items-center gap-1.5 cursor-pointer border border-transparent hover:border-rose-200"
                >
                  <X className="w-3.5 h-3.5" />
                  <span>Cancel & Discard</span>
                </button>

                <div className="flex items-center gap-2">
                  <button
                    type="button"
                    onClick={() => setStep('capture')}
                    className="px-4 py-2.5 rounded-xl border border-slate-300 text-xs font-bold text-slate-700 hover:bg-slate-100 transition-colors cursor-pointer"
                  >
                    Back to Photo
                  </button>
                  <button
                    type="button"
                    disabled={isSubmitting}
                    onClick={handlePublish}
                    className="px-6 py-2.5 rounded-xl bg-emerald-600 hover:bg-emerald-700 active:bg-emerald-800 text-white font-bold text-xs sm:text-sm shadow-md transition-all flex items-center gap-2 cursor-pointer"
                  >
                  {isSubmitting ? (
                    <>
                      <RefreshCw className="w-4 h-4 animate-spin" />
                      <span>Publishing...</span>
                    </>
                  ) : (
                    <>
                      <span>Publish Listing Now</span>
                      <ArrowRight className="w-4 h-4" />
                    </>
                  )}
                </button>
                </div>
              </div>

            </div>
          )}

          {/* STEP 4: PUBLISHED CELEBRATION */}
          {step === 'published' && finalListing && (
            <div className="py-8 px-4 text-center space-y-5">
              <div className="w-16 h-16 rounded-full bg-emerald-100 text-emerald-600 flex items-center justify-center mx-auto shadow-md">
                <CheckCircle2 className="w-10 h-10" />
              </div>

              <div>
                <h3 className="text-xl font-extrabold text-slate-900">
                  Item Listed in the Marketplace! 🎉
                </h3>
                <p className="text-xs text-slate-600 mt-1 max-w-md mx-auto">
                  Your surplus is now ready for neighbors in <strong>{finalListing.neighborhoodName}</strong>.
                </p>
              </div>

              {/* KPI & Impact Badge */}
              <div className="bg-emerald-50 rounded-2xl p-4 border border-emerald-200 max-w-md mx-auto flex items-center justify-around">
                <div>
                  <div className="text-[10px] text-slate-500 font-bold uppercase">Time-to-List</div>
                  <div className="text-base font-extrabold text-emerald-800 font-mono">
                    {finalListing.timeToListSeconds}s
                  </div>
                  <div className="text-[9px] text-emerald-600 font-medium">Target &lt; 20s ✓</div>
                </div>
                <div className="h-8 w-px bg-emerald-200" />
                <div>
                  <div className="text-[10px] text-slate-500 font-bold uppercase">Social Impact</div>
                  <div className="text-xs font-bold text-emerald-950 truncate max-w-[180px]">
                    {finalListing.impactMetric}
                  </div>
                  <div className="text-[9px] text-emerald-600 font-medium">Mutual Aid Added</div>
                </div>
              </div>

              <div className="pt-2">
                <button
                  onClick={handleResetAndClose}
                  className="px-6 py-2.5 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-xs sm:text-sm shadow-md transition-all"
                >
                  Done & View in Marketplace
                </button>
              </div>
            </div>
          )}

        </div>

      </div>
    </div>
  );
};
